package com.anafthdev.calcc.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF725c00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffe16e)
val md_theme_light_onPrimaryContainer = Color(0xFF231b00)
val md_theme_light_secondary = Color(0xFF685e40)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf0e2bc)
val md_theme_light_onSecondaryContainer = Color(0xFF211b04)
val md_theme_light_tertiary = Color(0xFF44664c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc7eccc)
val md_theme_light_onTertiaryContainer = Color(0xFF01210e)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbf7)
val md_theme_light_onBackground = Color(0xFF1d1b16)
val md_theme_light_surface = Color(0xFFfffbf7)
val md_theme_light_onSurface = Color(0xFF1d1b16)
val md_theme_light_surfaceVariant = Color(0xFFebe2d0)
val md_theme_light_onSurfaceVariant = Color(0xFF4b4639)
val md_theme_light_outline = Color(0xFF7d7767)
val md_theme_light_inverseOnSurface = Color(0xFFf6f0e7)
val md_theme_light_inverseSurface = Color(0xFF33302a)
val md_theme_light_inversePrimary = Color(0xFFe5c44a)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFe5c44a)
val md_theme_dark_onPrimary = Color(0xFF3c2f00)
val md_theme_dark_primaryContainer = Color(0xFF564500)
val md_theme_dark_onPrimaryContainer = Color(0xFFffe16e)
val md_theme_dark_secondary = Color(0xFFd3c6a1)
val md_theme_dark_onSecondary = Color(0xFF383016)
val md_theme_dark_secondaryContainer = Color(0xFF4f462a)
val md_theme_dark_onSecondaryContainer = Color(0xFFf0e2bc)
val md_theme_dark_tertiary = Color(0xFFabd0b1)
val md_theme_dark_onTertiary = Color(0xFF163721)
val md_theme_dark_tertiaryContainer = Color(0xFF2d4e36)
val md_theme_dark_onTertiaryContainer = Color(0xFFc7eccc)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1b16)
val md_theme_dark_onBackground = Color(0xFFe8e2d9)
val md_theme_dark_surface = Color(0xFF1d1b16)
val md_theme_dark_onSurface = Color(0xFFe8e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF4b4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFcec6b4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1b16)
val md_theme_dark_inverseSurface = Color(0xFFe8e2d9)
val md_theme_dark_inversePrimary = Color(0xFF725c00)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFFe8c959)
val error = Color(0xFFba1b1b)